### PR TITLE
Feature #158  Implement functionality for Blogs

### PR DESCRIPTION
**Pull request by LunarShadow152004**
### Feature #158

1. This PR Add feature of the issue #158 
2. This PR modifies/create the following 
      * Modified AlumniConnect/urls.py :  Added a new URL path /blogs.
      * Created forms.py : Added necessary forms for handling data input.
      * Updated models.py : Copied models.py from the feature/blog branch and Made minor modifications to adapt the existing models.
      * Created/Modified urls.py : Added necessary URL patterns for the blog functionality.
      * Modified views.py : Updated views to handle new and existing functionality as required.
 ###  Proof That The Changes are Working :-

https://github.com/BitByte-TPC/alumni/assets/163876039/b6649d7f-4065-4401-a881-ee421869d6fe

https://github.com/BitByte-TPC/alumni/assets/163876039/f29ca6a6-62cc-451e-9be6-29b0ddc7b05f

Thank You

### CODE REVIEW

**Comment by SamakshAgarwal1112** [comment]
@LunarShadow152004 The code quality is good and logic is . But a few changes are required.
- Redirect the page to `\blogs\`, whenever some unknown blog_id is passed in the url.
- Do the above same thing for all views that require some kind of key and redirect them accordingly.
- When the user selects 'Self' as the blog_type, then the user should be not required to enter the campaign. It should only be required when blog_type is 'Campaign'.
- Reuse the admin.py content from `feature\blog` branch.
- Deal with the integrity error whenever user tries to make a campaign without an end date.
- Fix the spelling of receiver in models.
- Set receiver in replies as empty string for default.

**Comment by LunarShadow152004** [comment]
@SamakshAgarwal1112  I have made the changes that you asked for.

**Comment by SamakshAgarwal1112** [comment]
@LunarShadow152004 Good work. Although you missed a few things.
- In campaign model, add `null=True` to date_ended, otherwise it causes an error while running migrations.
- In replies model, change the receiver to a foreign key instead as all receivers are gonna be the users only at the end.

**Comment by LunarShadow152004** [comment]
@SamakshAgarwal1112  My Discord username is lunarshadow15

**Comment by SamakshAgarwal1112** [comment]
@LunarShadow152004 Replies logic will be dealt with in detail when the HTML templates for it is ready. For now just make the requested changes and also, make sure when you change receiver to foreign key User, change logic for creating replies in views accordingly.

**Comment by LunarShadow152004** [comment]
@SamakshAgarwal1112  I have made required changes

**Pull request merged**
